"""add_photo_column

Revision ID: 66594e415101
Revises: b1db7192b270
Create Date: 2024-05-24 14:00:13.705064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66594e415101'
down_revision = 'b1db7192b270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
