"""add sleep questions

Revision ID: a92249536cda
Revises: 10ffaae2d406
Create Date: 2024-03-19 14:00:18.864991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a92249536cda'
down_revision = '10ffaae2d406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions_sleep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tofu', sa.String(length=255), nullable=True),
    sa.Column('processed_meat', sa.String(length=255), nullable=True),
    sa.Column('play_sport', sa.String(length=255), nullable=True),
    sa.Column('eat_weekend', sa.String(length=255), nullable=True),
    sa.Column('sleep_night', sa.String(length=255), nullable=True),
    sa.Column('sugary_drinks', sa.String(length=255), nullable=True),
    sa.Column('cows_milk', sa.String(length=255), nullable=True),
    sa.Column('fresh_cheeses', sa.String(length=255), nullable=True),
    sa.Column('miss_meals', sa.String(length=255), nullable=True),
    sa.Column('vegetable_drinks', sa.String(length=255), nullable=True),
    sa.Column('eat_fast', sa.String(length=255), nullable=True),
    sa.Column('cooked_vegetables', sa.String(length=255), nullable=True),
    sa.Column('low_fat_yogurt', sa.String(length=255), nullable=True),
    sa.Column('wake_up_eat_night', sa.String(length=255), nullable=True),
    sa.Column('hungry_during_day', sa.String(length=255), nullable=True),
    sa.Column('nuts', sa.String(length=255), nullable=True),
    sa.Column('fish', sa.String(length=255), nullable=True),
    sa.Column('fruits', sa.String(length=255), nullable=True),
    sa.Column('eggs', sa.String(length=255), nullable=True),
    sa.Column('whole_grains_food', sa.String(length=255), nullable=True),
    sa.Column('eat_uncontrollably', sa.String(length=255), nullable=True),
    sa.Column('alcoholic_beverages', sa.String(length=255), nullable=True),
    sa.Column('meat', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    op.drop_table('questions_sleep')
    # ### end Alembic commands ###
