"""+ sex

Revision ID: ee4a894b6d5c
Revises: a92249536cda
Create Date: 2024-03-22 17:56:32.476271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee4a894b6d5c'
down_revision = 'a92249536cda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions_sleep', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sex', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions_sleep', schema=None) as batch_op:
        batch_op.drop_column('sex')

    # ### end Alembic commands ###
