repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black --config /mnt/d/Project\ Habbits/eating-habits-tracker/site/.black .
        language: system
        types: [python]
        pass_filenames: false

      - id: flake8
        name: flake8
        entry: flake8 --config /mnt/d/Project\ Habbits/eating-habits-tracker/site/.flake8 .
        language: system
        types: [ python ]
        pass_filenames: false